apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ratetraffictargets.bb.com
spec:
  group: bb.com
  names:
    kind: RateTrafficTarget
    plural: ratetraffictargets
    singular: ratetraffictarget
    shortNames:
      - rtt
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                http:
                  properties:
                    timeoutSeconds:
                      type: integer
                    uri:
                      type: string
                    headers:
                      additionalProperties:
                        type: string
                      type: object
                    body:
                      type: string
                    method:
                      type: string
                  type: object
                rate:
                  type: integer
              required:
                - rate
                - http
              type: object
            status:
              properties:
                state:
                  enum:
                    - SCHEDULING
                    - FAILURE
                    - ERROR
                  type: string
              type: object
          type: object
      additionalPrinterColumns:
        - name: Target URI
          type: string
          description: Target URI value
          jsonPath: .spec.http.uri
        - name: Rate
          type: string
          description: Scheduling rate
          jsonPath: .spec.rate
        - name: State
          type: string
          description: TrafficTarget current state
          jsonPath: .status.state
      served: true
      storage: true
      subresources:
        status: { }