apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic-maker-service-account
  namespace: traffic-maker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traffic-maker-cluster-role
rules:
  - apiGroups: [ "bb.traffic-maker.com" ]
    verbs: [ "*" ]
    resources: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traffic-maker-cluster-role-binding
  namespace: traffic-maker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traffic-maker-cluster-role
subjects:
  - kind: ServiceAccount
    name: traffic-maker-service-account
    namespace: traffic-maker